name: CMake on multiple platforms (using CMakePresets)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        preset: [debug, sanitazers, release]

        include:
          - os: ubuntu-latest
            preset: debug
          - os: ubuntu-latest
            preset: sanitazers
          - os: ubuntu-latest
            preset: release

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build clang cmake
        shell: bash

      - name: Set version
        id: set_version
        run: |
          echo "VERSION=v${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Configure
        working-directory: language
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        working-directory: language
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Test
        working-directory: language
        if: matrix.preset != 'release'
        run: ctest --preset ${{ matrix.preset }} --output-on-failure
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Arch-${{ steps.set_version.outputs.VERSION }}-${{ matrix.preset }}
          path: language/build