name: Test DSL (Integration tests)

on:
  workflow_run:
    workflows: ["CMake on multiple platforms (using CMakePresets)"]
    types: 
      - completed

jobs:
  test-dsl:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: Arch-latest-debug
          path: artifacts

      - name: Show downloaded files
        run: ls -R artifacts

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python requirements
        run: |
          pip install --upgrade pip
          pip install -r converter/requirements.txt

      - name: Start Neo4j Docker Container
        run: |
          docker pull neo4j:latest
          docker run -d \
            --name neo4j-test \
            --publish=7474:7474 --publish=7687:7687 \
            --volume=$HOME/neo4j/data:/data \
            --env=NEO4J_AUTH=none \
            -e NEO4J_apoc_export_file_enabled=true \
            -e NEO4J_apoc_import_file_enabled=true \
            -e NEO4J_apoc_import_file_use__neo4j__config=true \
            -e NEO4J_PLUGINS='["apoc", "graph-data-science"]' \
            neo4j:latest

      - name: Wait for Neo4j to be ready
        run: |
          sleep 20
          - name: Run all example tests

      - name: Run All Tests
        run: ./scripts/test_all_examples.sh

      - name: Stop Neo4j container
        if: always()
        run: docker stop neo4j-test